server:
  port: 8886
eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://hatakiA.com:8888/eureka/
  instance:
    #hostname是标识主机，appname是标识分组的，等同于spring-application-name
    hostname: hatakiB.com
spring:
  application:
    name: EurekaServer

